# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T10:17:23+00:00



import argparse
import json
import os
from typing import *
from typing import Optional, Union

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import APIKeyHeader, BaseSecurity
from fastapi import Header, Path, Query
from pydantic import constr

from models import (
    AlreadyStreamedException,
    BulkPublishResponse,
    ConcurrentModificationException,
    DeleteDatasetResponse,
    DescribeDatasetResponse,
    DescribeIdentityPoolUsageResponse,
    DescribeIdentityUsageResponse,
    DuplicateRequestException,
    GetBulkPublishDetailsResponse,
    GetCognitoEventsResponse,
    GetIdentityPoolConfigurationResponse,
    IdentitypoolsIdentityPoolIdConfigurationPostRequest,
    IdentitypoolsIdentityPoolIdEventsPostRequest,
    IdentitypoolsIdentityPoolIdIdentitiesIdentityIdDatasetsDatasetNamePostRequest,
    IdentitypoolsIdentityPoolIdIdentityIdentityIdDevicePostRequest,
    InternalErrorException,
    InvalidConfigurationException,
    InvalidLambdaFunctionOutputException,
    InvalidParameterException,
    LambdaThrottledException,
    LimitExceededException,
    ListDatasetsResponse,
    ListIdentityPoolUsageResponse,
    ListRecordsResponse,
    NotAuthorizedException,
    RegisterDeviceResponse,
    ResourceConflictException,
    ResourceNotFoundException,
    SetIdentityPoolConfigurationResponse,
    SubscribeToDatasetResponse,
    TooManyRequestsException,
    UnsubscribeFromDatasetResponse,
    UpdateRecordsResponse,
)

app = MCPProxy(
    contact={
        'email': 'mike.ralphson@gmail.com',
        'name': 'Mike Ralphson',
        'url': 'https://github.com/mermade/aws2openapi',
        'x-twitter': 'PermittedSoc',
    },
    description='<fullname>Amazon Cognito Sync</fullname> <p>Amazon Cognito Sync provides an AWS service and client library that enable cross-device syncing of application-related user data. High-level client libraries are available for both iOS and Android. You can use these libraries to persist data locally so that it\'s available even if the device is offline. Developer credentials don\'t need to be stored on the mobile device to access the service. You can use Amazon Cognito to obtain a normalized user ID and credentials. User data is persisted in a dataset that can store up to 1 MB of key-value pairs, and you can have up to 20 datasets per user identity.</p> <p>With Amazon Cognito Sync, the data stored for each identity is accessible only to credentials assigned to that identity. In order to use the Cognito Sync service, you need to make API calls using credentials retrieved with <a href="http://docs.aws.amazon.com/cognitoidentity/latest/APIReference/Welcome.html">Amazon Cognito Identity service</a>.</p> <p>If you want to use Cognito Sync in an Android or iOS application, you will probably want to make API calls via the AWS Mobile SDK. To learn more, see the <a href="http://docs.aws.amazon.com/mobile/sdkforandroid/developerguide/cognito-sync.html">Developer Guide for Android</a> and the <a href="http://docs.aws.amazon.com/mobile/sdkforios/developerguide/cognito-sync.html">Developer Guide for iOS</a>.</p>',
    license={'name': 'Apache 2.0 License', 'url': 'http://www.apache.org/licenses/'},
    termsOfService='https://aws.amazon.com/service-terms/',
    title='Amazon Cognito Sync',
    version='2014-06-30',
    servers=[
        {
            'description': 'The Amazon Cognito Sync multi-region endpoint',
            'url': 'http://cognito-sync.{region}.amazonaws.com',
            'variables': {
                'region': {
                    'default': 'us-east-1',
                    'description': 'The AWS region',
                    'enum': [
                        'us-east-1',
                        'us-east-2',
                        'us-west-1',
                        'us-west-2',
                        'us-gov-west-1',
                        'us-gov-east-1',
                        'ca-central-1',
                        'eu-north-1',
                        'eu-west-1',
                        'eu-west-2',
                        'eu-west-3',
                        'eu-central-1',
                        'eu-south-1',
                        'af-south-1',
                        'ap-northeast-1',
                        'ap-northeast-2',
                        'ap-northeast-3',
                        'ap-southeast-1',
                        'ap-southeast-2',
                        'ap-east-1',
                        'ap-south-1',
                        'sa-east-1',
                        'me-south-1',
                    ],
                }
            },
        },
        {
            'description': 'The Amazon Cognito Sync multi-region endpoint',
            'url': 'https://cognito-sync.{region}.amazonaws.com',
            'variables': {
                'region': {
                    'default': 'us-east-1',
                    'description': 'The AWS region',
                    'enum': [
                        'us-east-1',
                        'us-east-2',
                        'us-west-1',
                        'us-west-2',
                        'us-gov-west-1',
                        'us-gov-east-1',
                        'ca-central-1',
                        'eu-north-1',
                        'eu-west-1',
                        'eu-west-2',
                        'eu-west-3',
                        'eu-central-1',
                        'eu-south-1',
                        'af-south-1',
                        'ap-northeast-1',
                        'ap-northeast-2',
                        'ap-northeast-3',
                        'ap-southeast-1',
                        'ap-southeast-2',
                        'ap-east-1',
                        'ap-south-1',
                        'sa-east-1',
                        'me-south-1',
                    ],
                }
            },
        },
        {
            'description': 'The Amazon Cognito Sync endpoint for China (Beijing) and China (Ningxia)',
            'url': 'http://cognito-sync.{region}.amazonaws.com.cn',
            'variables': {
                'region': {
                    'default': 'cn-north-1',
                    'description': 'The AWS region',
                    'enum': ['cn-north-1', 'cn-northwest-1'],
                }
            },
        },
        {
            'description': 'The Amazon Cognito Sync endpoint for China (Beijing) and China (Ningxia)',
            'url': 'https://cognito-sync.{region}.amazonaws.com.cn',
            'variables': {
                'region': {
                    'default': 'cn-north-1',
                    'description': 'The AWS region',
                    'enum': ['cn-north-1', 'cn-northwest-1'],
                }
            },
        },
    ],
)


@app.get(
    '/identitypools',
    description=""" <p>Gets a list of identity pools registered with Cognito.</p> <p>ListIdentityPoolUsage can only be called with developer credentials. You cannot make this API call with the temporary user credentials provided by Cognito Identity.</p> """,
    tags=['identity_pool_configuration', 'cognito_event_configuration'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def list_identity_pool_usage(
    next_token: Optional[str] = Query(None, alias='nextToken'),
    max_results: Optional[int] = Query(None, alias='maxResults'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/identitypools/{IdentityPoolId}',
    description=""" <p>Gets usage details (for example, data storage) about a particular identity pool.</p> <p>This API can only be called with developer credentials. You cannot call this API with the temporary user credentials provided by Cognito Identity.</p> """,
    tags=[
        'identity_pool_usage',
        'identity_pool_configuration',
        'cognito_event_configuration',
    ],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def describe_identity_pool_usage(
    identity_pool_id: constr(
        pattern=r'[\w-]+:[0-9a-f-]+', min_length=1, max_length=55
    ) = Path(..., alias='IdentityPoolId'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/identitypools/{IdentityPoolId}/bulkpublish',
    description=""" <p>Initiates a bulk publish of all existing datasets for an Identity Pool to the configured stream. Customers are limited to one successful bulk publish per 24 hours. Bulk publish is an asynchronous request, customers can see the status of the request via the GetBulkPublishDetails operation.</p><p>This API can only be called with developer credentials. You cannot call this API with the temporary user credentials provided by Cognito Identity.</p> """,
    tags=['identity_pool_configuration', 'cognito_event_configuration'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def bulk_publish(
    identity_pool_id: constr(
        pattern=r'[\w-]+:[0-9a-f-]+', min_length=1, max_length=55
    ) = Path(..., alias='IdentityPoolId'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/identitypools/{IdentityPoolId}/configuration',
    description=""" <p>Gets the configuration settings of an identity pool.</p><p>This API can only be called with developer credentials. You cannot call this API with the temporary user credentials provided by Cognito Identity.</p> """,
    tags=['identity_pool_configuration', 'cognito_event_configuration'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def get_identity_pool_configuration(
    identity_pool_id: constr(
        pattern=r'[\w-]+:[0-9a-f-]+', min_length=1, max_length=55
    ) = Path(..., alias='IdentityPoolId'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/identitypools/{IdentityPoolId}/configuration',
    description=""" <p>Sets the necessary configuration for push sync.</p><p>This API can only be called with developer credentials. You cannot call this API with the temporary user credentials provided by Cognito Identity.</p> """,
    tags=['identity_pool_configuration', 'cognito_event_configuration'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def set_identity_pool_configuration(
    identity_pool_id: constr(
        pattern=r'[\w-]+:[0-9a-f-]+', min_length=1, max_length=55
    ) = Path(..., alias='IdentityPoolId'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
    body: IdentitypoolsIdentityPoolIdConfigurationPostRequest = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/identitypools/{IdentityPoolId}/events',
    description=""" <p>Gets the events and the corresponding Lambda functions associated with an identity pool.</p><p>This API can only be called with developer credentials. You cannot call this API with the temporary user credentials provided by Cognito Identity.</p> """,
    tags=['identity_pool_configuration', 'cognito_event_configuration'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def get_cognito_events(
    identity_pool_id: constr(
        pattern=r'[\w-]+:[0-9a-f-]+', min_length=1, max_length=55
    ) = Path(..., alias='IdentityPoolId'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/identitypools/{IdentityPoolId}/events',
    description=""" <p>Sets the AWS Lambda function for a given event type for an identity pool. This request only updates the key/value pair specified. Other key/values pairs are not updated. To remove a key value pair, pass a empty value for the particular key.</p><p>This API can only be called with developer credentials. You cannot call this API with the temporary user credentials provided by Cognito Identity.</p> """,
    tags=[
        'identity_pool_usage',
        'identity_pool_configuration',
        'cognito_event_configuration',
    ],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def set_cognito_events(
    identity_pool_id: constr(
        pattern=r'[\w-]+:[0-9a-f-]+', min_length=1, max_length=55
    ) = Path(..., alias='IdentityPoolId'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
    body: IdentitypoolsIdentityPoolIdEventsPostRequest = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/identitypools/{IdentityPoolId}/getBulkPublishDetails',
    description=""" <p>Get the status of the last BulkPublish operation for an identity pool.</p><p>This API can only be called with developer credentials. You cannot call this API with the temporary user credentials provided by Cognito Identity.</p> """,
    tags=['identity_pool_configuration', 'cognito_event_configuration'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def get_bulk_publish_details(
    identity_pool_id: constr(
        pattern=r'[\w-]+:[0-9a-f-]+', min_length=1, max_length=55
    ) = Path(..., alias='IdentityPoolId'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/identitypools/{IdentityPoolId}/identities/{IdentityId}',
    description=""" <p>Gets usage information for an identity, including number of datasets and data usage.</p> <p>This API can be called with temporary user credentials provided by Cognito Identity or with developer credentials.</p> """,
    tags=['identity_pool_configuration', 'cognito_event_configuration'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def describe_identity_usage(
    identity_pool_id: constr(
        pattern=r'[\w-]+:[0-9a-f-]+', min_length=1, max_length=55
    ) = Path(..., alias='IdentityPoolId'),
    identity_id: constr(
        pattern=r'[\w-]+:[0-9a-f-]+', min_length=1, max_length=55
    ) = Path(..., alias='IdentityId'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/identitypools/{IdentityPoolId}/identities/{IdentityId}/datasets',
    description=""" <p>Lists datasets for an identity. With Amazon Cognito Sync, each identity has access only to its own data. Thus, the credentials used to make this API call need to have access to the identity data.</p> <p>ListDatasets can be called with temporary user credentials provided by Cognito Identity or with developer credentials. You should use the Cognito Identity credentials to make this API call.</p> """,
    tags=[
        'identity_pool_usage',
        'identity_pool_configuration',
        'cognito_event_configuration',
        'dataset_operations',
        'record_operations',
        'dataset_subscription_actions',
        'device_management',
    ],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def list_datasets(
    identity_pool_id: constr(
        pattern=r'[\w-]+:[0-9a-f-]+', min_length=1, max_length=55
    ) = Path(..., alias='IdentityPoolId'),
    identity_id: constr(
        pattern=r'[\w-]+:[0-9a-f-]+', min_length=1, max_length=55
    ) = Path(..., alias='IdentityId'),
    next_token: Optional[str] = Query(None, alias='nextToken'),
    max_results: Optional[int] = Query(None, alias='maxResults'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/identitypools/{IdentityPoolId}/identities/{IdentityId}/datasets/{DatasetName}',
    description=""" <p>Deletes the specific dataset. The dataset will be deleted permanently, and the action can't be undone. Datasets that this dataset was merged with will no longer report the merge. Any subsequent operation on this dataset will result in a ResourceNotFoundException.</p> <p>This API can be called with temporary user credentials provided by Cognito Identity or with developer credentials.</p> """,
    tags=['identity_pool_usage', 'dataset_operations', 'record_operations'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def delete_dataset(
    identity_pool_id: constr(
        pattern=r'[\w-]+:[0-9a-f-]+', min_length=1, max_length=55
    ) = Path(..., alias='IdentityPoolId'),
    identity_id: constr(
        pattern=r'[\w-]+:[0-9a-f-]+', min_length=1, max_length=55
    ) = Path(..., alias='IdentityId'),
    dataset_name: constr(
        pattern=r'[a-zA-Z0-9_.:-]+', min_length=1, max_length=128
    ) = Path(..., alias='DatasetName'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/identitypools/{IdentityPoolId}/identities/{IdentityId}/datasets/{DatasetName}',
    description=""" <p>Gets meta data about a dataset by identity and dataset name. With Amazon Cognito Sync, each identity has access only to its own data. Thus, the credentials used to make this API call need to have access to the identity data.</p> <p>This API can be called with temporary user credentials provided by Cognito Identity or with developer credentials. You should use Cognito Identity credentials to make this API call.</p> """,
    tags=['identity_pool_usage', 'dataset_operations'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def describe_dataset(
    identity_pool_id: constr(
        pattern=r'[\w-]+:[0-9a-f-]+', min_length=1, max_length=55
    ) = Path(..., alias='IdentityPoolId'),
    identity_id: constr(
        pattern=r'[\w-]+:[0-9a-f-]+', min_length=1, max_length=55
    ) = Path(..., alias='IdentityId'),
    dataset_name: constr(
        pattern=r'[a-zA-Z0-9_.:-]+', min_length=1, max_length=128
    ) = Path(..., alias='DatasetName'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/identitypools/{IdentityPoolId}/identities/{IdentityId}/datasets/{DatasetName}',
    description=""" <p>Posts updates to records and adds and deletes records for a dataset and user.</p> <p>The sync count in the record patch is your last known sync count for that record. The server will reject an UpdateRecords request with a ResourceConflictException if you try to patch a record with a new value but a stale sync count.</p><p>For example, if the sync count on the server is 5 for a key called highScore and you try and submit a new highScore with sync count of 4, the request will be rejected. To obtain the current sync count for a record, call ListRecords. On a successful update of the record, the response returns the new sync count for that record. You should present that sync count the next time you try to update that same record. When the record does not exist, specify the sync count as 0.</p> <p>This API can be called with temporary user credentials provided by Cognito Identity or with developer credentials.</p> """,
    tags=['identity_pool_usage', 'dataset_operations', 'record_operations'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def update_records(
    identity_pool_id: constr(
        pattern=r'[\w-]+:[0-9a-f-]+', min_length=1, max_length=55
    ) = Path(..., alias='IdentityPoolId'),
    identity_id: constr(
        pattern=r'[\w-]+:[0-9a-f-]+', min_length=1, max_length=55
    ) = Path(..., alias='IdentityId'),
    dataset_name: constr(
        pattern=r'[a-zA-Z0-9_.:-]+', min_length=1, max_length=128
    ) = Path(..., alias='DatasetName'),
    x_amz__client__context: Optional[str] = Header(None, alias='x-amz-Client-Context'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
    body: IdentitypoolsIdentityPoolIdIdentitiesIdentityIdDatasetsDatasetNamePostRequest = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/identitypools/{IdentityPoolId}/identities/{IdentityId}/datasets/{DatasetName}/records',
    description=""" <p>Gets paginated records, optionally changed after a particular sync count for a dataset and identity. With Amazon Cognito Sync, each identity has access only to its own data. Thus, the credentials used to make this API call need to have access to the identity data.</p> <p>ListRecords can be called with temporary user credentials provided by Cognito Identity or with developer credentials. You should use Cognito Identity credentials to make this API call.</p> """,
    tags=['identity_pool_usage', 'dataset_operations'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def list_records(
    identity_pool_id: constr(
        pattern=r'[\w-]+:[0-9a-f-]+', min_length=1, max_length=55
    ) = Path(..., alias='IdentityPoolId'),
    identity_id: constr(
        pattern=r'[\w-]+:[0-9a-f-]+', min_length=1, max_length=55
    ) = Path(..., alias='IdentityId'),
    dataset_name: constr(
        pattern=r'[a-zA-Z0-9_.:-]+', min_length=1, max_length=128
    ) = Path(..., alias='DatasetName'),
    last_sync_count: Optional[int] = Query(None, alias='lastSyncCount'),
    next_token: Optional[str] = Query(None, alias='nextToken'),
    max_results: Optional[int] = Query(None, alias='maxResults'),
    sync_session_token: Optional[str] = Query(None, alias='syncSessionToken'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/identitypools/{IdentityPoolId}/identities/{IdentityId}/datasets/{DatasetName}/subscriptions/{DeviceId}',
    description=""" <p>Unsubscribes from receiving notifications when a dataset is modified by another device.</p><p>This API can only be called with temporary credentials provided by Cognito Identity. You cannot call this API with developer credentials.</p> """,
    tags=[
        'identity_pool_usage',
        'dataset_operations',
        'record_operations',
        'device_management',
    ],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def unsubscribe_from_dataset(
    identity_pool_id: constr(
        pattern=r'[\w-]+:[0-9a-f-]+', min_length=1, max_length=55
    ) = Path(..., alias='IdentityPoolId'),
    identity_id: constr(
        pattern=r'[\w-]+:[0-9a-f-]+', min_length=1, max_length=55
    ) = Path(..., alias='IdentityId'),
    dataset_name: constr(
        pattern=r'[a-zA-Z0-9_.:-]+', min_length=1, max_length=128
    ) = Path(..., alias='DatasetName'),
    device_id: constr(min_length=1, max_length=256) = Path(..., alias='DeviceId'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/identitypools/{IdentityPoolId}/identities/{IdentityId}/datasets/{DatasetName}/subscriptions/{DeviceId}',
    description=""" <p>Subscribes to receive notifications when a dataset is modified by another device.</p><p>This API can only be called with temporary credentials provided by Cognito Identity. You cannot call this API with developer credentials.</p> """,
    tags=['dataset_operations', 'device_management'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def subscribe_to_dataset(
    identity_pool_id: constr(
        pattern=r'[\w-]+:[0-9a-f-]+', min_length=1, max_length=55
    ) = Path(..., alias='IdentityPoolId'),
    identity_id: constr(
        pattern=r'[\w-]+:[0-9a-f-]+', min_length=1, max_length=55
    ) = Path(..., alias='IdentityId'),
    dataset_name: constr(
        pattern=r'[a-zA-Z0-9_.:-]+', min_length=1, max_length=128
    ) = Path(..., alias='DatasetName'),
    device_id: constr(min_length=1, max_length=256) = Path(..., alias='DeviceId'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/identitypools/{IdentityPoolId}/identity/{IdentityId}/device',
    description=""" <p>Registers a device to receive push sync notifications.</p><p>This API can only be called with temporary credentials provided by Cognito Identity. You cannot call this API with developer credentials.</p> """,
    tags=['device_management', 'identity_pool_usage'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def register_device(
    identity_pool_id: constr(
        pattern=r'[\w-]+:[0-9a-f-]+', min_length=1, max_length=55
    ) = Path(..., alias='IdentityPoolId'),
    identity_id: constr(
        pattern=r'[\w-]+:[0-9a-f-]+', min_length=1, max_length=55
    ) = Path(..., alias='IdentityId'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
    body: IdentitypoolsIdentityPoolIdIdentityIdentityIdDevicePostRequest = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
